***Q1***

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
arr2=arr+2
arr2

array([3, 4, 5, 6, 7])

In [3]:
arr3=arr*3
arr3

array([ 3,  6,  9, 12, 15])

In [5]:
arr_div=arr/2
arr_div

array([0.5, 1. , 1.5, 2. , 2.5])

***Q2***

In [27]:
arr = np.array([1, 2, 3, 6, 4, 5])
reverse=arr[::-1]
reverse

array([5, 4, 6, 3, 2, 1])

In [30]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
values,counts=np.unique(x,return_counts=True)
most_freq=values[np.argmax(counts)]
most_freq


1

In [32]:
indices=np.where(x==most_freq)
indices

(array([0, 5, 7, 8, 9]),)

In [31]:
indices=np.where(x==most_freq)[0]
indices

array([0, 5, 7, 8, 9])

In [33]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [34]:
values,counts=np.unique(y,return_counts=True)
most_freq=values[np.argmax(counts)]
most_freq

1

In [35]:
indices=np.where(y==most_freq)[0]
indices

array([0, 1, 2])

***Q3***

In [8]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[0,1]

20

In [9]:
arr[2,0]

70

***Q4***

In [10]:
navnoor=np.linspace(10,100,25)
navnoor.ndim

1

In [11]:
navnoor.shape

(25,)

In [12]:
navnoor.size

25

In [13]:
navnoor.dtype

dtype('float64')

In [14]:
navnoor.nbytes

200

In [15]:
navoor_reshape=navnoor.reshape(5,5)
navoor_reshape

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ],
       [ 28.75,  32.5 ,  36.25,  40.  ,  43.75],
       [ 47.5 ,  51.25,  55.  ,  58.75,  62.5 ],
       [ 66.25,  70.  ,  73.75,  77.5 ,  81.25],
       [ 85.  ,  88.75,  92.5 ,  96.25, 100.  ]])

In [18]:
navnoor_t=navoor_reshape.T
navnoor_t

array([[ 10.  ,  28.75,  47.5 ,  66.25,  85.  ],
       [ 13.75,  32.5 ,  51.25,  70.  ,  88.75],
       [ 17.5 ,  36.25,  55.  ,  73.75,  92.5 ],
       [ 21.25,  40.  ,  58.75,  77.5 ,  96.25],
       [ 25.  ,  43.75,  62.5 ,  81.25, 100.  ]])

***Q5***

In [19]:
ucs420_navnoor=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
np.mean(ucs420_navnoor)

43.333333333333336

In [20]:
np.median(ucs420_navnoor)

37.5

In [21]:
np.max(ucs420_navnoor)

90

In [22]:
np.min(ucs420_navnoor)

10

In [23]:
np.unique(ucs420_navnoor)

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [24]:
reshaped_ucs420_navnoor=ucs420_navnoor.reshape(4,3)
reshaped_ucs420_navnoor

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [26]:
resized_ucs420_ucs420_navnoor=np.resize(ucs420_navnoor,(2,3))
resized_ucs420_ucs420_navnoor

array([[10, 20, 30],
       [40, 50, 60]])